# Generated by Django 4.1 on 2022-08-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cerated',
            new_name='created',
        ),
    ]
