# Generated by Django 4.1 on 2022-08-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_cerated_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dec',
            new_name='description',
        ),
    ]
